version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: dataviz_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: eliana20062004
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=dataviz_db
      - DB_USER=postgres
      - DB_PASS=eliana20062004
    ports:
      - "8050:8050"
    restart: unless-stopped

volumes:
  pgdata:
